repos:
-   repo: https://github.com/phantomcyber/dev-cicd-tools
    rev: v1.17
    hooks:
    -   id: org-hook
    -   id: package-app-dependencies
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--no-verify', '--exclude-files', '^crowdstrikeoauthapi.json$']
