name: Linting
on: [push, pull_request]
jobs:
  lint: 
    # Run per push for internal contributers. This isn't possible for forked pull requests,
    # so we'll need to run on PR events for external contributers.
    # String comparison below is case insensitive.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
     - uses: 'phantomcyber/dev-cicd-tools/github-actions/lint@main'
